#!/usr/bin/env bash

set -Eeuo pipefail

echo "Executing: $0 $*"

[[ "$1" = "final" ]] && {
	rm -rf /usr/lib/sysimage/rpm/.rpm.lock /usr/lib/sysimage/rpm/*
	rm -rf /var/log/journal/*
	dnf install -y --releasever 36 fedora-release sssd-client

	systemctl enable systemd-networkd
	systemctl enable systemd-resolved

	USERNAME="builder"
	useradd -m -U -s /usr/bin/zsh -G wheel "$USERNAME"
	passwd -d "$USERNAME"
	chmod -R g+rwXs "/home/$USERNAME"
}

exit 0
